Repository mdrokz/badminton_tracker, pull requests merged in 2022-06, with the labels that each got.

#5 2 implement dialog to input match data
  lib/constants.dart
  lib/httpClient.dart
  lib/main.dart
  lib/types/badminton.dart
  lib/types/github.dart
  lib/widgets.dart
Labels: enhancement, UI, API

#6 Fix: overflow errors in UI & state management fix for dropdown
  lib/main.dart
  lib/widgets/MWCard.dart
Labels: bug, UI

#4 1 implement card prokit
  android/app/build.gradle
  fonts/Icons.ttf
  lib/constants.dart
  lib/httpClient.dart
  lib/main.dart
  lib/types/badminton.dart
  lib/types/github.dart
  lib/utils/AppColors.dart
  lib/utils/AppConstants.dart
  lib/utils/AppWidget.dart
  lib/utils/Icons.dart
  lib/widgets.dart
  lib/widgets/MWCard.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, UI, API

#8 Revamp Match Card UI
  lib/main.dart
  lib/widgets/MWCard.dart
  pubspec.yaml
Labels: enhancement, UI, rework
